apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: myapp
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - name: myapp
        image: mydockerhubusername/blue-green-demo:blue
        ports:
        - containerPort: 80
        env:
        - name: COLOR
          value: "blue"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"