apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: myapp
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
      - name: myapp
        image: mydockerhubusername/blue-green-demo:green
        ports:
        - containerPort: 80
        env:
        - name: COLOR
          value: "green"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"