name: Blue-Green CI/CD

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/blue-green-demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push blue image
      run: |
        docker build -t $IMAGE_NAME:blue --build-arg COLOR=blue .
        docker push $IMAGE_NAME:blue

    - name: Build and push green image
      run: |
        docker build -t $IMAGE_NAME:green --build-arg COLOR=green .
        docker push $IMAGE_NAME:green

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployments/blue-deployment.yaml
        kubectl apply -f deployments/green-deployment.yaml
        kubectl apply -f deployments/service.yaml